apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-test-www
  namespace: canary-test
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: canary-test-www
  template:
    metadata:
      labels:
        app: canary-test-www
    spec:
      containers:
      - name: www
        image: ghcr.io/fase29/canary-test-www:0.3
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet: { path: /, port: 80 }
          initialDelaySeconds: 2
          periodSeconds: 5
        resources:
          requests: { cpu: 10m, memory: 16Mi }
          limits:   { memory: 64Mi }
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 2
      steps:
      - setWeight: 20
      - analysis:                      # automatic gate
          templates:
          - templateName: healthz-check
      - pause: {}                      # manual gate
      - setWeight: 40
      - pause: {}
      - setWeight: 60
      - analysis:                      # automatic gate
          templates:
          - templateName: healthz-check
      - pause: {}
      - setWeight: 80
      - pause: {}
